### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by Fabrimat** [rgbcraft/Industrial-Engineering#1]
- [ ] Reimplementare le cose della vecchia mod
- [x] Cassaforte con codice/password
- [x] Compressed blocks dei minerali vanilla
- [ ] Conquistare il mondo
- [ ] Radioattività nel mondo (con blocco creative)
